from __future__ import annotations

from pathlib import Path


MODULE_DIR = Path(__file__).resolve().parent
DEFAULT_EXAMPLE_SOURCE = MODULE_DIR / "xml_example" / "fk-inhome.com.ua.xml"
DEFAULT_EXAMPLE_SUPPLEMENTAL_SOURCE = MODULE_DIR / "xml_example" / "fk-inhome.com.ua=2.xml"
DEFAULT_DOWNLOAD_DIR = MODULE_DIR / "downloaded"
DEFAULT_DOWNLOADED_SOURCE = DEFAULT_DOWNLOAD_DIR / "fk-inhome.com.ua.rozetka.xml"
DEFAULT_DOWNLOADED_SUPPLEMENTAL_SOURCE = (
    DEFAULT_DOWNLOAD_DIR / "fk-inhome.com.ua.prom.xml"
)
DEFAULT_SOURCE = DEFAULT_EXAMPLE_SOURCE
DEFAULT_SUPPLEMENTAL_SOURCE = DEFAULT_EXAMPLE_SUPPLEMENTAL_SOURCE
DEFAULT_OUTPUT_DIR = MODULE_DIR / "generated"
DEFAULT_CONTENT_NAME = "content_feed.json"
DEFAULT_PROPOSITIONS_NAME = "propositions_feed.json"


__all__ = [
    "DEFAULT_CONTENT_NAME",
    "DEFAULT_DOWNLOADED_SOURCE",
    "DEFAULT_DOWNLOADED_SUPPLEMENTAL_SOURCE",
    "DEFAULT_DOWNLOAD_DIR",
    "DEFAULT_EXAMPLE_SOURCE",
    "DEFAULT_EXAMPLE_SUPPLEMENTAL_SOURCE",
    "DEFAULT_OUTPUT_DIR",
    "DEFAULT_PROPOSITIONS_NAME",
    "DEFAULT_SOURCE",
    "DEFAULT_SUPPLEMENTAL_SOURCE",
    "MODULE_DIR",
]
